In [ ]:
import numpy as np

In [2]:
array = np.array([1,2,3,4,5])
array
print(type(array))

<class 'numpy.ndarray'>


In [ ]:
array2 = array + 1
array2

In [8]:
array2 + array

array([ 3,  5,  7,  9, 11])

In [9]:
array2*array

array([ 2,  6, 12, 20, 30])

In [10]:
array[0]

1

In [11]:
array.shape

(5,)

In [13]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
array[2]

3

In [15]:
tang_list = [1,2,3,4,5]
tang_array = np.array(tang_list)
tang_array

array([1, 2, 3, 4, 5])

In [16]:
type(tang_array)

numpy.ndarray

In [17]:
tang_array.dtype

dtype('int32')

In [18]:
tang_array.itemsize

4

In [19]:
tang_array.shape

(5,)

In [20]:
tang_array.size

5

In [21]:
np.size(tang_array)

5

In [23]:
np.shape(tang_array)

(5,)

In [24]:
tang_array.ndim

1

In [32]:
tang_array

array([6, 6, 6, 6, 6])

In [30]:
tang_array

array([6, 6, 6, 6, 6])

In [33]:
tang_list = [1,2,3,4,5]
tang_array = np.array(tang_list)
tang_array[0]

1

In [35]:
tang_array[1:3]

array([2, 3])

In [37]:
tang_array[-3:]

array([3, 4, 5])

In [39]:
tang_array = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
tang_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
tang_array.shape

(3, 3)

In [41]:
tang_array.size

9

In [42]:
tang_array.ndim

2

In [44]:
tang_array[1,1]


5

In [45]:
tang_array[1,1] = 10
tang_array

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [46]:
tang_array[1]

array([ 4, 10,  6])

In [55]:
tang_array[:,1]

array([ 2, 10,  8])

In [57]:
tang_array[2,1:3]


array([8, 9])

In [58]:
tang_array

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [59]:
tang_array2 = tang_array
tang_array2 

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [60]:
tang_array2[1,1] = 100
tang_array2

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [61]:
tang_array

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [63]:
tang_array2 = tang_array.copy()
tang_array2

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [64]:
tang_array2[1,1] = 10000
tang_array2

array([[    1,     2,     3],
       [    4, 10000,     6],
       [    7,     8,     9]])

In [65]:
tang_array

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [66]:
tang_array = np.arange(0,100,10)
tang_array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [67]:
mask = np.array([0,0,0,1,1,1,0,0,1,1], dtype=bool)
mask

array([False, False, False,  True,  True,  True, False, False,  True,
        True])

In [68]:
tang_array[mask]

array([30, 40, 50, 80, 90])

In [76]:
random_array = np.random.rand(10)
random_array

array([0.94262409, 0.88693276, 0.50416219, 0.22654139, 0.72129603,
       0.32538017, 0.15843051, 0.40908079, 0.80076408, 0.28746843])

In [77]:
mask = random_array > 0.5
mask

array([ True,  True,  True, False,  True, False, False, False,  True,
       False])

In [78]:
tang_array[mask]

array([ 0, 10, 20, 40, 80])

In [79]:
tang_array = np.array([10,20,30,40,50])
tang_array > 30

array([False, False, False,  True,  True])

In [80]:
np.where(tang_array > 30)

(array([3, 4], dtype=int32),)

In [81]:
tang_array[np.where(tang_array > 30)]

array([40, 50])

In [103]:
tang_array = np.array([1,2,3,4,5],dtype=np.float32)
tang_array

array(['H', '1'], dtype='<U11')

In [104]:
tang_array.dtype

dtype('<U11')

In [96]:
tang_array.nbytes

40

In [106]:
tang_array = np.array([1,10,3.5,'str'], dtype=object)
tang_array

array([1, 10, 3.5, 'str'], dtype=object)

In [107]:
tang_array * 2

array([2, 20, 7.0, 'strstr'], dtype=object)

In [111]:
tang_array = np.array([1,2,3,4,5])
np.asarray(tang_array,dtype = np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)

In [112]:
tang_array

array([1, 2, 3, 4, 5])

In [113]:
tang_array2 = np.asarray(tang_array,dtype = np.float32)

In [114]:
tang_array2

array([1., 2., 3., 4., 5.], dtype=float32)

In [115]:
tang_array


array([1, 2, 3, 4, 5])

In [116]:
tang_array.astype(np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)

In [117]:
tang_array

array([1, 2, 3, 4, 5])

In [176]:
tang_array = np.array([[4,2,3],[1,5,6]])
tang_array

array([[4, 2, 3],
       [1, 5, 6]])

In [126]:
np.sum(tang_array)

21

In [130]:
np.sum(tang_array, axis=0)

array([5, 7, 9])

In [155]:
tang_array.ndim

2

In [160]:
np.sum(tang_array,axis=1)

array([ 6, 15])

In [161]:
tang_array.prod()

720

In [163]:
tang_array.prod(axis=0)

array([ 4, 10, 18])

In [165]:
tang_array.prod(axis=1)

array([  6, 120])

In [166]:
tang_array.min()

1

In [167]:
tang_array.min(axis=0)

array([1, 2, 3])

In [168]:
tang_array.min(axis=1)

array([1, 4])

In [169]:
tang_array.max()


6

In [172]:
tang_array.argmin()

0

In [177]:
tang_array.argmin(axis=0)

array([1, 0, 0], dtype=int32)

In [178]:
tang_array.argmin(axis=1)

array([1, 0], dtype=int32)

In [179]:
tang_array.argmax()

5

In [180]:
tang_array.mean()

3.5

In [181]:
tang_array.mean(axis=0)

array([2.5, 3.5, 4.5])

In [182]:
tang_array.std()

1.707825127659933

In [183]:
tang_array.std(axis=1)

array([0.81649658, 2.1602469 ])

In [184]:
tang_array.var()

2.9166666666666665

In [191]:
tang_array = np.array([[100,3,4],[0,555,3]])
tang_array

array([[100,   3,   4],
       [  0, 555,   3]])

In [192]:
tang_array.clip(2,4)

array([[4, 3, 4],
       [2, 4, 3]])

In [201]:
tang_array = np.array([1.5,3.56,6.51])

In [202]:
tang_array.round()

array([2., 4., 7.])

In [204]:
tang_array.round(decimals=1)

array([1.5, 3.6, 6.5])

In [206]:
tang_array = np.array([[1.5,1.3,7.5],
                     [5.6,7.8,1.2]])
tang_array

array([[1.5, 1.3, 7.5],
       [5.6, 7.8, 1.2]])

In [207]:
np.sort(tang_array)

array([[1.3, 1.5, 7.5],
       [1.2, 5.6, 7.8]])

In [210]:
np.sort(tang_array, axis=0)


array([[1.5, 1.3, 1.2],
       [5.6, 7.8, 7.5]])

In [212]:
tang_array

array([[1.5, 1.3, 7.5],
       [5.6, 7.8, 1.2]])

In [213]:
np.argsort(tang_array)

array([[1, 0, 2],
       [2, 0, 1]], dtype=int32)

In [217]:
tang_array = np.linspace(0,10,10)
tang_array

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [220]:
values = np.array([2.5,6.5,9.5])


[2.5 6.5 9.5]


In [222]:
np.searchsorted(tang_array, values)

array([3, 6, 9], dtype=int32)

In [251]:
tang_array = np.array([[1,0,6],
                     [1,7,0],
                     [2,3,1],
                     [2,4,0]])
tang_array

array([[1, 0, 6],
       [1, 7, 0],
       [2, 3, 1],
       [2, 4, 0]])

In [253]:
# np.lexsort(x , y) 先按照y來排序, 再按照x來排序
index = np.lexsort([-1*tang_array[:,0],tang_array[:,2]])
index

# 1 3 2 0
# 2 3 0 1
# 3 1 2 0

array([3, 1, 2, 0], dtype=int32)

In [254]:
tang_array = tang_array[index]
tang_array

array([[2, 4, 0],
       [1, 7, 0],
       [2, 3, 1],
       [1, 0, 6]])

In [19]:
import numpy as np
tang_array = np.arange(10)
tang_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# shape , reshape 功能一樣,改變array的排列, .shape = x,y ; .reshape(x,y)
tang_array.shape

(10,)

In [20]:
tang_array.shape = 1,10

In [21]:
tang_array

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [18]:
tang_array.reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [51]:
tang_array = np.arange(10)
tang_array.shape

(10,)

In [23]:
tang_array = tang_array[np.newaxis,:]
tang_array.shape

(1, 10)

In [24]:
tang_array

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [42]:
tang_array = np.arange(10)
tang_array.shape

(10,)

In [37]:
tang_array = tang_array[:,np.newaxis]
tang_array.shape

(10, 1)

In [38]:
tang_array

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [44]:
tang_array = tang_array[:,np.newaxis,np.newaxis]


In [45]:
tang_array.shape

(10, 1, 1, 1, 1)

In [46]:
tang_array = tang_array.squeeze()
tang_array.shape

(10,)

In [52]:
tang_array.shape = 2,5

In [53]:
tang_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [49]:
# .transpose() 與 .T 的效果一樣, 都是轉置
tang_array.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [54]:
tang_array.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [55]:
tang_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [56]:
a = np.array([[123,456,678],[3214,456,134]])
a

array([[ 123,  456,  678],
       [3214,  456,  134]])

In [58]:
b = np.array([[1235,3124,432],[43,13,134]])
b

array([[1235, 3124,  432],
       [  43,   13,  134]])

In [60]:
# np.concatenate((a,b)) 數組的連接
c = np.concatenate((a,b))
c

array([[ 123,  456,  678],
       [3214,  456,  134],
       [1235, 3124,  432],
       [  43,   13,  134]])

In [61]:
c = np.concatenate((a,b), axis = 0)
c

array([[ 123,  456,  678],
       [3214,  456,  134],
       [1235, 3124,  432],
       [  43,   13,  134]])

In [62]:
c = np.concatenate((a,b), axis = 1)
c

array([[ 123,  456,  678, 1235, 3124,  432],
       [3214,  456,  134,   43,   13,  134]])

In [63]:
c.shape

(2, 6)

In [64]:
np.vstack((a,b))

array([[ 123,  456,  678],
       [3214,  456,  134],
       [1235, 3124,  432],
       [  43,   13,  134]])

In [65]:
np.hstack((a,b))

array([[ 123,  456,  678, 1235, 3124,  432],
       [3214,  456,  134,   43,   13,  134]])

In [79]:
a

array([[ 123,  456,  678],
       [3214,  456,  134]])

In [67]:
# .flatten() 與 ravel() 效果一樣, 將array壓平成 1*n
a.flatten()

array([ 123,  456,  678, 3214,  456,  134])

In [72]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
b.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
np.arange(2,20,2,dtype=np.float32)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.], dtype=float32)

In [7]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [8]:
np.logspace(0,1,5)

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

In [9]:
x = np.linspace(-10,10,5)
x

array([-10.,  -5.,   0.,   5.,  10.])

In [10]:
y = np.linspace(-10,10,5)
y

array([-10.,  -5.,   0.,   5.,  10.])

In [11]:
x, y = np.meshgrid(x,y)

In [12]:
x

array([[-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.]])

In [13]:
y

array([[-10., -10., -10., -10., -10.],
       [ -5.,  -5.,  -5.,  -5.,  -5.],
       [  0.,   0.,   0.,   0.,   0.],
       [  5.,   5.,   5.,   5.,   5.],
       [ 10.,  10.,  10.,  10.,  10.]])

In [14]:
np.r_[0:10:1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.c_[0:10:1]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [16]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.ones((3,3)) * 8

array([[8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.]])

In [20]:
np.ones((3,3),dtype = np.float32)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [23]:
a = np.empty(6)
a

array([0., 0., 0., 0., 0., 0.])

In [24]:
a.shape

(6,)

In [26]:
a.fill(1)
a

array([1., 1., 1., 1., 1., 1.])

In [27]:
tang_array = np.array([1,2,3,4])
tang_array

array([1, 2, 3, 4])

In [28]:
np.zeros_like(tang_array)

array([0, 0, 0, 0])

In [29]:
np.ones_like(tang_array)

array([1, 1, 1, 1])

In [34]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
import numpy as np
x = np.array([7,5])
y = np.array([3,2])
np.multiply(x,y)

array([21, 10])

In [5]:
np.dot(x,y)

31

In [7]:
x.shape

(2,)

In [8]:
y.shape

(2,)

In [9]:
x.shape = 2,1
x

array([[7],
       [5]])

In [10]:
x.shape

(2, 1)

In [12]:
y.shape = 1,2
y

array([[3, 2]])

In [15]:
print(x.shape)
print(y.shape) 

(2, 1)
(1, 2)


In [16]:
# shape一樣要對應, 才能使用np.dot() (2,1)*(1,2) = (2,2)
np.dot(x,y)

array([[21, 14],
       [15, 10]])

In [17]:
np.dot(y,x)

array([[31]])

In [25]:
x = np.array([1,1,1])
y = np.array([[1,2,3],[4,5,6]])
print(x * y)

[[1 2 3]
 [4 5 6]]


In [38]:
y = np.array([3,1,1,4])
x = np.array([1000,1,1,0])
x == y

array([False,  True,  True, False])

In [39]:
np.logical_and(x,y)

array([ True,  True,  True, False])

In [40]:
np.logical_or(x,y)

array([ True,  True,  True,  True])

In [42]:
# logical_not為返回邏輯運算後的相反值
np.logical_not(x,y)

array([0, 0, 0, 1])

In [43]:
# np.random.rand的值都是從0到1
np.random.rand(3,2)

array([[0.54204932, 0.25089928],
       [0.79200641, 0.04846474],
       [0.53482994, 0.05628985]])

In [54]:
# 返回隨機的整數, 包含0但不包含10
np.random.randint(10, size = (5,4))

array([[1, 3, 5, 3],
       [2, 7, 7, 1],
       [7, 0, 4, 1],
       [9, 5, 8, 4],
       [8, 9, 1, 0]])

In [55]:
np.random.rand()

0.7469796439058735

In [79]:
np.random.random_sample()

0.9341444395396484

In [84]:
# 0~9 三個數
np.random.randint(0,10,3)

array([8, 2, 9])

In [85]:
# 常態分配
mu, sigma = 0, 0.1
np.random.normal(mu, sigma, 10)

array([-0.08691763, -0.10067508, -0.08799577,  0.08311951, -0.02921479,
        0.00530302, -0.11198287,  0.10946261, -0.15869641, -0.00119029])

In [86]:
# np.set_printoptions(precision = x), x為小數點後幾位
np.set_printoptions(precision = 3)
mu, sigma = 0,0.1
np.random.normal(mu, sigma, 10)

array([ 0.038,  0.05 ,  0.021,  0.089, -0.046, -0.043,  0.06 , -0.144,
        0.138,  0.01 ])

In [87]:
tang_array = np.arange(10)
tang_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
# np.random.shuffle 對array洗牌
np.random.shuffle(tang_array)
tang_array

array([3, 1, 8, 9, 0, 7, 5, 6, 4, 2])

In [250]:
# np.random.seed(x)使以下函數的隨機數值固定不變, x可以隨機設置
np.random.seed(100)
mu, sigma = 0,0.1
np.random.normal(mu, sigma, 10)

array([-0.175,  0.034,  0.115, -0.025,  0.098,  0.051,  0.022, -0.107,
       -0.019,  0.026])

In [262]:
np.random.seed(0)
x1 = np.random.rand(5)
x2 = np.random.rand(5)
x3 = np.random.rand(5)

print(x1)
print(x2)
print(x3)

[0.549 0.715 0.603 0.545 0.424]
[0.646 0.438 0.892 0.964 0.383]
[0.792 0.529 0.568 0.926 0.071]


In [275]:
# 使用numpy讀寫數據
# 使用magic function(%%writefile)在上面不能有註釋
import numpy as np

In [273]:
%%writefile tang.txt
1 2 3 4 5 6
2 3 5 8 7 9 

Writing tang.txt


In [277]:
data = []
with open('tang.txt') as f:
    for lines in f.readlines():
        fields = lines.split()
        cur_data = [float(x) for x in fields]
        data.append(cur_data)
data = np.array(data)
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 8., 7., 9.]])

In [279]:
data = np.loadtxt('tang.txt')
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 8., 7., 9.]])

In [282]:
%%writefile yu.txt
2 3 4 5 6
6 7 8 8 9 

Overwriting yu.txt


In [283]:
data = np.loadtxt('yu.txt')
data

array([[2., 3., 4., 5., 6.],
       [6., 7., 8., 8., 9.]])

In [293]:
%%writefile tang2.txt
1;2;3;4;5;6
2;3;5;8;7;9

Overwriting tang2.txt


In [294]:
data = np.loadtxt('tang2.txt', delimiter = ';')
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 8., 7., 9.]])

In [295]:
%%writefile tang2.txt
x,y,z,w,a,b
1,2,3,4,5,6
2,3,5,8,7,9

Overwriting tang2.txt


In [302]:
# skiprows: 去掉幾行
# delimiter=',' 分隔符
data = np.loadtxt('tang2.txt',delimiter = ',', skiprows=1)
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 8., 7., 9.]])

In [314]:
# usecols=(0,1,4) 指定使用哪幾列, 使用第0,1,4列
data = np.loadtxt('tang2.txt',delimiter = ',' ,skiprows=1,usecols=(0,1,4))
data

array([[1., 2., 5.],
       [2., 3., 7.]])

In [319]:
tang_array = np.array([[1,2,3],[4,5,6]])

In [320]:
np.savetxt('tang4.txt', tang_array)
# 1.000000000000000000e+00 2.000000000000000000e+00 3.000000000000000000e+00
# 4.000000000000000000e+00 5.000000000000000000e+00 6.000000000000000000e+00

In [321]:
np.savetxt('tang5.txt', tang_array,fmt='%d')
# 1 2 3
# 4 5 6

In [323]:
np.savetxt('tang6.txt', tang_array, fmt='%d', delimiter = ',')
# 1,2,3
# 4,5,6

In [324]:
np.savetxt('tang7.txt', tang_array,fmt='%.2f',delimiter = ',')
# 1.00,2.00,3.00
# 4.00,5.00,6.00

In [325]:
# 讀寫array結構
tang_array = np.array([[1,2,3],[4,5,6]])
np.save('tang_array.npy',tang_array)

In [326]:
tang = np.load('tang_array.npy')
tang

array([[1, 2, 3],
       [4, 5, 6]])

In [327]:
tang_array2 = np.arange(10)
tang_array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [328]:
# Save several arrays into a single file in uncompressed .npz format.
np.savez('tang.npz',a=tang_array,b=tang_array2)

In [329]:
data = np.load('tang.npz')
data.keys()

KeysView(NpzFile 'tang.npz' with keys: a, b)

In [330]:
data['a']

array([[1, 2, 3],
       [4, 5, 6]])

In [331]:
data['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])